import React from "react";
//<!-- spinner generated by https://loading.io/ -->
import spinner from "../../images/desktop/Spinner-1s-68px.svg";

const Loader = () => {
  return (
    <div>
      <span>
        <img src={spinner} alt="Loading..." />
      </span>
      <p>Loading...</p>
    </div>
  );
};

export default Loader;
